### ISSUE TITLE
Foto's missen alt tag

### ISSUE THREAD

**Issue by Robin1224** [julia-stevens/the-client-website#2]
Er zijn een aantal foto's in jouw HTML die een lege `alt` tag hebben.

https://github.com/julia-stevens/the-client-website/blob/7f8e5e1d8716b878eced6e68dd58d38beef80484/index.html#L55-L58

Probeer altijd de `alt` tag van foto's in te vullen, zodat mensen met een screenreader weten wat er op de foto staat. Een `alt` tag wordt namelijk opgelezen om foto's te omschrijven wanneer mensen met een screenreader de pagina bezoeken, net als het `aria-label` attribuut dat je op andere plekken gebruikt. [Meer info](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attributes)

**Suggestie:** Probeer de `alt` tags van de foto's op je pagina in te vullen met een beschrijving van de foto. Zet het woord "foto" er trouwens niet in, de screenreader noemt namelijk al dat het een foto is voordat het de `alt` tag leest.

**Comment by julia-stevens** [comment]
Aangepast: dcd83268ded9b8aa79cb7e69ad96cb69e3e448fb

**Comment by julia-stevens** [comment]
Aangepast: dcd83268ded9b8aa79cb7e69ad96cb69e3e448fb
