### ISSUE TITLE
Layout CSS review

### ISSUE THREAD

**Issue by kimnikitaschijf** [julia-stevens/the-client-website#26]
**CSS:**
Layout is netjes! Heel ruim en overzichtelijk. Rustig kleuren palette wat goed aansluit bij de huisstijl van Veronica. Ziet er super uit.
Je css is goed duidelijk ingedeeld. 

**Schetsen:**
Duidelijke breakdown schetsen en wireframes. Ze laten goed zien wat je wilt gaan maken. De breakdown schets is heel goed te overzien en daardoor goed uit te werken. 

**_Weinig op aan te merken! Ga zo door!! :) 👍_**

**Comment by MarsGotBars** [comment]
## Review Marcin
mobile ziet er netjes uit volgens design uit.
### issues
- Wel zie ik dat de mobile nav die inschuift, de secondary-menu blokkeert, waardoor je hier niet op kan klikken.
  - misschien is het een idee om het main-days element onderdeel te maken van een div samen met de secondary-menu ipv dat het 2 aparte ul's zijn
- op desktop valt het whatsapp icoon onder de scrollbar
- de dagen hebben een verticale scrollbar, is deze nodig?

**Comment by julia-stevens** [comment]
Ik heb de scroll bar op de dagen weggehaald & de header wat aangepast, waardoor het whatsapp logo hier niet meer onder valt; https://julia-stevens.github.io/the-client-website/
