### ISSUE TITLE
aria-label op dagen

### ISSUE THREAD

**Issue by Robin1224** [julia-stevens/the-client-website#3]
Bij het dagen overzicht gebruik je afkortingen van de dagen:

https://github.com/julia-stevens/the-client-website/blob/7f8e5e1d8716b878eced6e68dd58d38beef80484/index.html#L34-L44

Hier is niks mis mee, en er wordt nog niet van je verwacht dat je de `aria-label` tag gebruikt, maar omdat je op andere plekken in je HTML al wel de `aria-label` gebruikt hebt, kun je deze hier ook goed toepassen. Een screenreader kan deze afkortingen namelijk niet begrijpen en zal niet begrijpbaar het dagen overzicht uitlezen.

**Suggestie:** Voeg bij de links in het dagenoverzicht `aria-label` tags toe.

**Comment by julia-stevens** [comment]
Aangepast: aaf3c8ab643ebedb8d742304d148eba7f34eb7be
