### ISSUE TITLE
Refactor CSS

### ISSUE THREAD

**Issue by Akikosophia** [julia-stevens/the-client-website#33]
We hadden even gekeken naar de code die je had geschreven. Je gaf zelf al aan dat je op de volgorde hebt gewerkt hoe je je code hebt geschreven.

Je kunt alleen de aanpassing maken en de volgorde gebruiken van je html structuur. De nav en header en body kunnen boven aan en dan kun je waar de cards komen te staan daaronder plaatsen!

Je bent goed op weg :)

Even een voorbeeld:

```
body {
    font-family: sans-serif;
    line-height: 1.5;
}

nav {
    display: flex;
    ul {
        list-style: none;
    }
}
 
Hier kun je dan de kaartjes plaatsen!
Cards

footer {
    font-size: smaller;
}

```

**Comment by julia-stevens** [comment]
Ik heb de volgorde van mijn CSS aangepast: 

* <img width="300" alt="image" src="https://github.com/user-attachments/assets/23e65225-bedc-4919-8d5e-7cbb2f7ae111">
* <img width="300" alt="image" src="https://github.com/user-attachments/assets/8f588528-ca20-4c75-9595-623870323cea">
* <img width="300" alt="image" src="https://github.com/user-attachments/assets/ccbefa15-c927-4150-a8ce-05576dee6bcb">

Commit: 4ba7888c44c8653420750e311e54a88387676adf

**Comment by julia-stevens** [comment]
Ik heb de volgorde van mijn CSS aangepast: 

* <img width="300" alt="image" src="https://github.com/user-attachments/assets/23e65225-bedc-4919-8d5e-7cbb2f7ae111">
* <img width="300" alt="image" src="https://github.com/user-attachments/assets/8f588528-ca20-4c75-9595-623870323cea">
* <img width="300" alt="image" src="https://github.com/user-attachments/assets/ccbefa15-c927-4150-a8ce-05576dee6bcb">

Commit: 4ba7888c44c8653420750e311e54a88387676adf
