### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by Robin1224** [julia-stevens/the-client-website#4]
https://github.com/julia-stevens/the-client-website/blob/7f8e5e1d8716b878eced6e68dd58d38beef80484/index.html#L6

Kleine opmerking, maar vergeet je `<title>` niet aan te passen! Het is nu namelijk nog de standaard `the-client-case`, in plaats van een passende pagina titel.

**Suggestie:** Verander het `<title>` element naar een passende pagina titel.

**Comment by julia-stevens** [comment]
Aangepast naar ''Programmering'' dc98b77296d672bd823b9a03f1e0fdbcc225ea9c
