### ISSUE TITLE
Code/Design Review

### ISSUE THREAD

**Issue by irisvw** [julia-stevens/the-client-website#6]
### W3 validator
- Geen errors of warnings :)

### HTML
- Misschien de `<nav>` in een `<header>` tag zetten?
- de nav-hamburger div zou beter een `<ul>` kunnen zijn, met de children als list items.
- hetzelfde bij secundair-menu en main-days.
- Structuur is netjes en overzichtelijk.
- `<hgroup>` had ik nog niet van gehoord, handig :)

### Design
- Wireframes en schetsen zijn mooi en overzichtelijk. Er is rekening gehouden met verschillende schermformaten.

**Comment by julia-stevens** [comment]
Aangepast: 
* 5a1d19ea60bf9a8c6e1d33d1c3b5fe31c0f3527c
* e6fc90d60c9e47e1285555c69ac8c2fbface67b8
