### ISSUE TITLE
aria labels

### ISSUE THREAD

**Issue by KoopReynders** [julia-stevens/the-client-website#7]
https://github.com/julia-stevens/the-client-website/blob/7f8e5e1d8716b878eced6e68dd58d38beef80484/index.html#L10

Als je nette, semantische HTML schrijft heb je in principe geen Aria nodig.

**Comment by julia-stevens** [comment]
Ik heb de structuur van de code enigszins aangepast (`nav` in een `header`), waardoor ik hier geen aria-label meer gebruik: 5a1d19ea60bf9a8c6e1d33d1c3b5fe31c0f3527c
