### ISSUE TITLE
Article in Article

### ISSUE THREAD

**Issue by KoopReynders** [julia-stevens/the-client-website#9]
Je nest hier een article in een article. Zou je dat ook andes kunnen oplossen? 

> The `<article>` HTML element represents a self-contained composition in a document, page, application, or site, which is intended to be independently distributable or reusable
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article

https://github.com/julia-stevens/the-client-website/blob/7f8e5e1d8716b878eced6e68dd58d38beef80484/index.html#L46-L60

**Comment by julia-stevens** [comment]
Ik heb de code anders gestructureerd, namelijk het tweede menu en een overzicht van de dagen van de week toegevoegd aan de header. Hierdoor is de `main` alleen de `article` s, dus ik heb het parent `article` element weggehaald. 

https://github.com/julia-stevens/the-client-website/blob/a9c77a06fd0066b59c481b0ae6a3b9edcaab0cfb/index.html#L47-L175

Commit: a9c77a06fd0066b59c481b0ae6a3b9edcaab0cfb
